apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: system
  sources:
  - chart: cert-manager
    repoURL: oci://quay.io/jetstack/charts/cert-manager
    path: .
    targetRevision: 1.19.2
    helm:
      releaseName: cert-manager
      valueFiles:
        - $values/apps_system/cert-manager/values.yaml
  - repoURL: 'git@github.com:pirish/cluster-base.git'
    targetRevision: HEAD
    ref: values
  # - repoURL: 'git@github.com:pirish/cluster-base.git'
  #   targetRevision: HEAD
  #   path: additional_manifests/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true